services:
  valkey: 
    image: 'bitnami/valkey:latest'
    volumes: 
      - valkey-data:/bitnami/valkey/data
    ports:
      - "6379:6379"
    env_file:
      - valkey.dev.env
  
  # cdn:
  #   image: quay.io/minio/minio:RELEASE.2024-05-10T01-41-38Z
  #   command: server --console-address ":9001" /data
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   healthcheck:
  #     test: ["CMD", "mc", "ready", "local"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #   env_file: 
  #     - minio.dev.env
  #   volumes:
  #     - netbeams-cdn:/data

  # nginx:
  #   image: nginx:1.19.2-alpine
  #   hostname: nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - cdn


volumes:
  valkey-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./data/valkey
  netbeams-cdn:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./data/cdn/