# This is the BeamMP-Server config file.
# Help & Documentation: `https://docs.beammp.com/server/server-maintenance/`
# IMPORTANT: Fill in the AuthKey with the key you got from `https://keymaster.beammp.com/` on the left under "Keys"

[General]
Name = "BeamMP Server"
Port = 30814
# AuthKey has to be filled out in order to run the server
AuthKey = "REPLACE_ME"
# Whether to log chat messages in the console / log
LogChat = true
# Add custom identifying tags to your server to make it easier to find. Format should be TagA,TagB,TagC. Note the comma seperation.
Tags = "Freeroam"
Debug = false
Private = false
MaxCars = 2
MaxPlayers = 8
Map = "/levels/gridmap_v2/info.json"
Description = "BeamMP Default Description"
ResourceFolder = "Resources"


# Not supported by NetBeams yet - As these options are from the official server
[Misc]
# Hides the periodic update message which notifies you of a new server version. You should really keep this on and always update as soon as possible. For more information visit https://wiki.beammp.com/en/home/server-maintenance#updating-the-server. An update message will always appear at startup regardless.
ImScaredOfUpdates = false
# You can turn on/off the SendErrors message you get on startup here
SendErrorsShowMessage = true
# If SendErrors is `true`, the server will send helpful info about crashes and other issues back to the BeamMP developers. This info may include your config, who is on your server at the time of the error, and similar general information. This kind of data is vital in helping us diagnose and fix issues faster. This has no impact on server performance. You can opt-out of this system by setting this to `false`
SendErrors = true

# Custom configurations specific to NetBeams servers
[NetBeams]
# The url of the master node which should be connected to (or empty if this is the master node)
MasterNode = "localhost"
# The port of the master node, (defaults to 30815)
MasterPort = 30815
# The log level of the node (overridden using environment variable NETBEAMS_LOG_LEVEL, default "info")
LogLevel = "info"
# The path to the log file of the server (usually /logs/netbeams.log)
LogFile = "/logs/netbeams.log"
# The url of the mod server (if one is being used, leave blank for auto-configuration)
ModServer = ""
